name: Deploy to pythonAnywhere
run-name: deploy-to-pythonanywhere
on: 
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jaliaga/test_flask_app:latest

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run container
        run: docker run --rm -dp 5050:5000 --name testme jaliaga/test_flask_app:latest 
      - name: run test
        run: |
          docker ps
          sleep 5
          curl -v localhost:5050
          if [[ $(curl --write-out %{http_code}  -s localhost:5050/health --output /dev/null) -eq 200 ]]; then echo "ok" && exit 0; else echo "not ok - health endpoint did not respond ok" && exit 1; fi

  security:
    environment: dev
    runs-on: ubuntu-20.04
    needs: tests
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t my_image:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my_image:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  deploy:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 deploy/main.py

  post-check:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "I would do my post-check"

    

