name: Deploy to pythonAnywhere
run-name: deploy-to-pythonanywhere
on: 
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    continue-on-error: true
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - run: echo "I would do my tests"
      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v3
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      #- name: Build and push
      #  uses: docker/build-push-action@v5
      #  with:
      #    push: true
      #    tags: docker/ent_24:latest

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "I would do my tests"

  security:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "I would do my sec-tests"

  deploy:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 deploy/main.py

  post-check:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "I would do my post-check"

    

